name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # This ensures the site deploys from the gh-pages branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload static site files
        uses: actions/upload-pages-artifact@v1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
